// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebScrapperProxy.Database;
#nullable disable

namespace WebScrapperProxy.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("WebScrapperProxy.Models.Extracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaminhoArquivoJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataFinal")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeLinhas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadePaginas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Extracoes");
                });
#pragma warning restore 612, 618
        }
    }
}
